#!/bin/bash

gstatus=`git status --porcelain`

if [ ${#gstatus} -ne 0 ]
then
    eval $(ssh-agent)
    ssh-add "C:\Users\i7\.ssh\id_rsa" -t 180
    git add --all
    git commit -m "Automated sync: $gstatus"
    git pull --rebase
    git push

fi